config/routes.rb
Rails.application.routes.draw do
  resources :relationships

  resources :ribbits

  resources :sessions, only: [:create, :destroy]
  resources :users

  get 'logout', to: 'sessions#destroy', as: 'logout' 

  match 'buddies', to: 'users#buddies', via: :get

  root 'users#new'

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

	belongs_to :follower, class_name: 'User'
	belongs_to :followed, class_name: 'User'
end

app/models/ribbit.rb
class Ribbit < ActiveRecord::Base

	belongs_to :user

	default_scope {order('created_at DESC')}

	validates :content, length:{maximum: 140}
end

app/models/user.rb
require 'digest/md5'

class User < ActiveRecord::Base
	
	has_many :ribbits, dependent: :destroy
	has_many :follower_relationships, class_name: 'Relationship', foreign_key: 'followed_id'
	has_many :followed_relationships, class_name: 'Relationship', foreign_key: 'follower_id'
	has_many :followers, through: :follower_relationships, source: :follower
	has_many :followeds, through: :followed_relationships, source: :followed

	has_secure_password

	before_validation :prep_email
	before_save :create_avatar_url

	validates :email, presence: true, uniqueness: true, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create}
	validates :username, presence: true, uniqueness: true
	validates :name, presence: true

	def following? user
		self.followeds.include? user
	end

	def follow user
		Relationship.create follower_id: self.id, followed_id: user.id
	end

	def unfollow user
		Relationship.find_by(followed_id: user.id).destroy
	end

	private
		def prep_email
			self.email = self.email.strip.downcase if self.email
		end

	def create_avatar_url
		self.avatar_url = "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(self.email)}?s=50"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  	def current_user
  		@current_user ||= session[:user_id] && User.find(session[:user_id])
  	end

  	helper_method :current_user

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def create
		@user = User.find(params[:relationship][:followed_id])
		current_user.follow(@user)
		redirect_to @user
	end	

	def destroy
		@user = Relationship.find(params[:id]).followed
		current_user.unfollow(@user)
		redirect_to @user
	end	
end

app/controllers/ribbits_controller.rb
class RibbitsController < ApplicationController

	def index
		@ribbits = Ribbit.all
		@ribbit = Ribbit.new
	end

	def create
		@ribbit = current_user.ribbits.new(ribbit_params)

		if @ribbit.save
			flash[:success] = 'Success'
		else
			flash.now[:error] = 'Error'			
		end
		redirect_to root_path
	end


	private

		def ribbit_params
			params.require(:ribbit).permit(:content)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
  	user = User.find_by username: params[:username]
  	if user and user.authenticate(params[:password])
  		flash[:success] = 'You are logged in'
  		session[:user_id] = user.id
  		redirect_to root_path
  	else
  		flash[:error] = 'Wrong credentials'
  		redirect_to root_path
  	end
  end

  def destroy
  	flash[:success] = 'Logged out'
  	session[:user_id] = nil
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
		@ribbit = Ribbit.new
	end

	def new
		if current_user
			redirect_to buddies_path
		else
			@user = User.new
		end
	end

	def create
		@user = User.new(user_params)

		if @user.save
			flash[:success] = 'Account was successfully created'
			redirect_to @user
		else
			flash.now[:error] = 'Error occured'
			render :new
		end
	end

	def show
		@user = User.find(params[:id])
		@ribbit = Ribbit.new
		@relationship = Relationship.where(follower_id: current_user.id, followed_id: @user.id).first_or_initialize if current_user
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to @user, notice: "Profile updated"
		else
			render :edit
		end
	end

	def buddies
		if current_user
			# buddies_ids = current_user.followeds.map{|user| user.id}.push(current_user.id)
			# buddies_ids = current_user.followeds.map(&:id).push(current_user.id)
			buddies_ids = current_user.followeds.ids.push(current_user.id)
			@ribbit = Ribbit.new
			@ribbits = Ribbit.where(user_id: buddies_ids)
		else
			redirect_to root_path
		end
	end

	def user_params
		params.require(:user).permit(:avatar_url, :bio, :email, :name, :password, :password_confirmation, :username)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationsips_helper.rb
module RelationsipsHelper
end

app/helpers/ribbits_helper.rb
module RibbitsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ribbit</title>
  <link rel="stylesheet/less" href="/style.less">
  <script src="/less.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<div class='wrepper'>
		<img src='/gfx/logo.png'>
		<span>Twitter Clone</span>
		<% if current_user %>
			<%= link_to "Buddies' Ribbits", buddies_path %>
			<%= link_to 'Public Ribbits', ribbits_path %>
			<%= link_to 'Public Profiles', users_path %>
			<%= link_to 'My Profile', current_user %>
			<%= link_to 'Log Out', logout_path %>
		<%else%>
			<%= form_tag sessions_path do %>
				<%= text_field_tag :username, nil, placeholder: "username"%>
				<%= password_field_tag :password, nil, placeholder: 'password' %>
				<%= submit_tag 'Log In' %>
			<%end%>
		<%end%>
	</div><!--end wrapper -->
</header>
<div id='content'>
	<div class='wrapper'>
		<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, class: "flash #{name}" %>
		<%end%>
		<%= yield %>
	</div>
</div>
<footer>
	<div class='wrapper'>
		Ribbit - A Twitter Clone Tutorial <img src="/gfx/logo-nettuts.png">
	</div>
</footer>
</body>
</html>

app/views/partials/_new_form.html.erb
<div class='panel right'>
	<h1>Create a Ribbit</h1>
	<%= form_for @ribbit do |f| %>
		<%= f.text_area :content, class: 'ribbitText', id: 'ribbitText'%>

		<%= f.submit 'Ribbit!'%>
		<span id='charCount'>0</span>
	<%end%>
</div>

app/views/ribbits/index.html.erb
<% if current_user %>
	<%= render 'partials/new_form' %>
<%end%>
<div class='panel left'>
	<h1>Public Ribbits</h1>
	<% @ribbits.each do |ribbit| %>
		<div class='ribbitWrapper'>
			<a href="<%= user_path ribbit.user.id%>">
				<img class='avatar' src="<%= ribbit.user.avatar_url%>">
			</a>
			<span class='name'><%= ribbit.user.name %></span>
			@<%= ribbit.user.username %>
			<span class='time'><%= time_ago_in_words(ribbit.created_at) %></span>
			<p><%= ribbit.content %></p>
		</div>
	<%end%>
</div>

app/views/users/buddies.html.erb
<% if current_user %>
	<%= render 'partials/new_form' %>
<%end%>
<div class='panel left'>
	<h1>Buddies Ribbits</h1>
	<% @ribbits.each do |ribbit| %>
		<div class='ribbitWrapper'>
			<a href="<%= user_path ribbit.user.id%>">
				<img class='avatar' src="<%= ribbit.user.avatar_url%>">
			</a>
			<span class='name'><%= ribbit.user.name %></span>
			@<%= ribbit.user.username %>
			<span class='time'><%= time_ago_in_words(ribbit.created_at) %></span>
			<p><%= ribbit.content %></p>
		</div>
	<%end%>
</div>

app/views/users/edit.html.erb
<div class='panel left'>
	<h1>Edit Profile</h1>
	<%= form_for @user do |f| %>
		<% if @user.errors.any? %>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<%end%>
			</ul>
		<%end%>
		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :username %>
		<%= f.text_field :username %>

		<%= f.label :email %>
		<%= f.email_field :email%>

		<%= f.label :bio %>
		<%= f.text_area :bio %>

		<%= f.label :password %>
		<%= f.password_field :password %>

		<%= f.label :password_confirmation, 'Confirm' %>
		<%= f.password_field :password_confirmation %>

		<%= f.submit %>
	<% end %>
</div>

app/views/users/index.html.erb
<% if current_user %>
	<%= render 'partials/new_form' %>
<%end%>

<div class='panel left'>
	<h1>Public Profiles</h1>
	<% @users.each do |user| %>
		<div class='ribbitWrapper'>
			<a href="<%= user_path user %>">
				<img class='avatar' src="<%= user.avatar_url%>">
				<span class='name'><%= user.name %></span>
			</a>
			@<%= user.username %>
			<p>
				<%= pluralize(user.ribbits.length, 'Ribbit') %>
				<span class='spacing'><%= pluralize(user.followers.length,'Follower')%></span>
				<span class='spacing'><%= user.followeds.length %> Following</span>
			</p>
			<% if user.bio %>
				<p><%= user.bio %></p>
			<% elsif user.ribbits.first %>
				<p>
					<%= user.ribbits.first.content %>
				</p>
			<% end %>
		</div>
	<%end%>

</div>

app/views/users/new.html.erb
<img src="/gfx/frog.jpg">
<div class='panel right'>
	<h1>New to Ribbit?</h1>
	<div>
		<%= form_for @user do |f| %>
			<% if @user.errors.any? %>
				<ul>
					<% @user.errors.full_messages.each do |error| %>
						<li><%= error %></li>
					<%end%>
				</ul>
			<%end%>

			<%= f.text_field :email, placeholder: 'email' %>
			<%= f.text_field :name, placeholder: 'name' %>
			<%= f.text_field :username, placeholder: 'username'%>
			<%= f.password_field :password, placeholder: 'password' %>
			<%= f.password_field :password_confirmation, placeholder: 'confirm password' %>

			<%= f.submit 'Create Account' %>
		<%end%>
	</div>
</div>

app/views/users/show.html.erb
<% if current_user %>
	<%= render 'partials/new_form'%>
<%end%>
<div id='ribbits' class='panel left'>
	<h1>
		Ribbit Profile
		<%= link_to("(edit profile)", edit_user_path(@user)) if @user == current_user %> 
	</h1>
	<div class='ribbitWrapper'>
		<img class='avatar' src="<%= @user.avatar_url%>">
		<span class='name'><%= @user.name %></span> @<%= @user.username%>
		<p>
			<%= pluralize(@user.ribbits.length, 'Ribbit') %>
			<span class='spacing'><%= @user.followers.length %> Follwers</span>
			<span class='spacing'><%= @user.followeds.length %> Follwing</span>
			<% if @user.bio %>
				<p><%= @user.bio %></p>
			<%end%>
			<% if current_user && @user != current_user %>
				<% if current_user.following? @user %>
					<%= form_for @relationship, method: :delete do |f| %>
						<%= f.submit 'Unfollow' %>
					<%end%>
				<%else%>
					<%= form_for @relationship do |f| %>
						<%= f.hidden_field :followed_id, value: @user.id %>
						<%= f.submit 'Follow'%>
					<%end%>
				<%end%>
			<%end%>
		</p>
	</div>
</div>
<div class='panel left'>
	<h1>Ribbits</h1>
	<% @user.ribbits.each do |ribbit|%>
		<div class='ribbitWrapper'>
			<img class='avatar' src="<%= ribbit.user.avatar_url%>">
			<span class='name'><%= ribbit.user.name %></span>
			@<%= ribbit.user.username %>
			<span class='time'><%= time_ago_in_words(ribbit.created_at) %></span>
			<p><%= ribbit.content %></p>
		</div>
	<%end%>
</div>